// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Currency.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from Currency.proto</summary>
  public static partial class CurrencyReflection {

    #region Descriptor
    /// <summary>File descriptor for Currency.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static CurrencyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5DdXJyZW5jeS5wcm90bxIFUHJvdG8qQAoIQ3VycmVuY3kSBwoDQ05ZEAAS",
            "BwoDSEtEEAESBwoDVVNEEAISBwoDRVVSEAMSBwoDSlBZEAQSBwoDU0dEEAVi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.Currency), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Currency {
    [pbr::OriginalName("CNY")] Cny = 0,
    [pbr::OriginalName("HKD")] Hkd = 1,
    [pbr::OriginalName("USD")] Usd = 2,
    [pbr::OriginalName("EUR")] Eur = 3,
    [pbr::OriginalName("JPY")] Jpy = 4,
    [pbr::OriginalName("SGD")] Sgd = 5,
  }

  #endregion

}

#endregion Designer generated code
