// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Exchange.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from Exchange.proto</summary>
  public static partial class ExchangeReflection {

    #region Descriptor
    /// <summary>File descriptor for Exchange.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExchangeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5FeGNoYW5nZS5wcm90bxIFUHJvdG8qRQoIRXhjaGFuZ2USBwoDU1NFEAAS",
            "CAoEU1pTRRABEgkKBUNGRkVYEAISCAoEU0hGRRADEgcKA0RDRRAEEggKBENa",
            "Q0UQBWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.Exchange), }, null));
    }
    #endregion

  }
  #region Enums
  public enum Exchange {
    /// <summary>
    //// SH
    /// </summary>
    [pbr::OriginalName("SSE")] Sse = 0,
    /// <summary>
    //// SZ
    /// </summary>
    [pbr::OriginalName("SZSE")] Szse = 1,
    /// <summary>
    //// CF
    /// </summary>
    [pbr::OriginalName("CFFEX")] Cffex = 2,
    /// <summary>
    //// SF
    /// </summary>
    [pbr::OriginalName("SHFE")] Shfe = 3,
    /// <summary>
    //// DE
    /// </summary>
    [pbr::OriginalName("DCE")] Dce = 4,
    /// <summary>
    //// CE
    /// </summary>
    [pbr::OriginalName("CZCE")] Czce = 5,
  }

  #endregion

}

#endregion Designer generated code
