// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Order.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from Order.proto</summary>
  public static partial class OrderReflection {

    #region Descriptor
    /// <summary>File descriptor for Order.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OrderReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtPcmRlci5wcm90bxIFUHJvdG8aDkV4Y2hhbmdlLnByb3RvIoEDCgVPcmRl",
            "chIKCgJpZBgBIAEoBBISCgppbnN0cnVtZW50GAIgASgJEiEKCGV4Y2hhbmdl",
            "GAMgASgOMg8uUHJvdG8uRXhjaGFuZ2USEgoKY291bnRlcl9pZBgEIAEoCRIT",
            "CgtleGNoYW5nZV9pZBgFIAEoCRIMCgRub3RlGAYgASgJEg0KBXByaWNlGAcg",
            "ASgBEhoKEmF2Z19leGVjdXRlZF9wcmljZRgIIAEoARIOCgZ2b2x1bWUYCSAB",
            "KAUSFwoPZXhlY3V0ZWRfdm9sdW1lGAogASgFEhkKBHNpZGUYCyABKA4yCy5Q",
            "cm90by5TaWRlEiwKDnRpbWVfY29uZGl0aW9uGAwgASgOMhQuUHJvdG8uVGlt",
            "ZUNvbmRpdGlvbhIeCgR0eXBlGA0gASgOMhAuUHJvdG8uT3JkZXJUeXBlEiIK",
            "BnN0YXR1cxgOIAEoDjISLlByb3RvLk9yZGVyU3RhdHVzEgwKBHRpbWUYDyAB",
            "KAQSDwoHbGF0ZW5jeRgQIAEoBSqMAQoEU2lkZRIHCgNCdXkQABIICgRTZWxs",
            "EAESDAoIQnV5Q292ZXIQAhIRCg1CdXlDb3ZlclRvZGF5EAMSFQoRQnV5Q292",
            "ZXJZZXN0ZXJkYXkQBBINCglTZWxsQ292ZXIQBRISCg5TZWxsQ292ZXJUb2Rh",
            "eRAGEhYKElNlbGxDb3Zlclllc3RlcmRheRAHKiEKDVRpbWVDb25kaXRpb24S",
            "BwoDR1REEAASBwoDSU9DEAEqIgoJT3JkZXJUeXBlEgkKBUxpbWl0EAASCgoG",
            "TWFya2V0EAEqlQEKC09yZGVyU3RhdHVzEg0KCVVuZGVmaW5lZBAAEgkKBUxv",
            "Y2FsEAESDQoJU3VibWl0dGVkEAISBwoDTmV3EAMSEQoNUGFydGlhbEZpbGxl",
            "ZBAEEgoKBkZpbGxlZBAFEhkKFVBhcnRpYWxGaWxsZWRDYW5jZWxlZBAGEgwK",
            "CENhbmNlbGVkEAcSDAoIUmVqZWN0ZWQQCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ExchangeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.Side), typeof(global::Proto.TimeCondition), typeof(global::Proto.OrderType), typeof(global::Proto.OrderStatus), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.Order), global::Proto.Order.Parser, new[]{ "Id", "Instrument", "Exchange", "CounterId", "ExchangeId", "Note", "Price", "AvgExecutedPrice", "Volume", "ExecutedVolume", "Side", "TimeCondition", "Type", "Status", "Time", "Latency" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum Side {
    [pbr::OriginalName("Buy")] Buy = 0,
    [pbr::OriginalName("Sell")] Sell = 1,
    [pbr::OriginalName("BuyCover")] BuyCover = 2,
    [pbr::OriginalName("BuyCoverToday")] BuyCoverToday = 3,
    [pbr::OriginalName("BuyCoverYesterday")] BuyCoverYesterday = 4,
    [pbr::OriginalName("SellCover")] SellCover = 5,
    [pbr::OriginalName("SellCoverToday")] SellCoverToday = 6,
    [pbr::OriginalName("SellCoverYesterday")] SellCoverYesterday = 7,
  }

  public enum TimeCondition {
    [pbr::OriginalName("GTD")] Gtd = 0,
    [pbr::OriginalName("IOC")] Ioc = 1,
  }

  public enum OrderType {
    [pbr::OriginalName("Limit")] Limit = 0,
    [pbr::OriginalName("Market")] Market = 1,
  }

  public enum OrderStatus {
    [pbr::OriginalName("Undefined")] Undefined = 0,
    [pbr::OriginalName("Local")] Local = 1,
    [pbr::OriginalName("Submitted")] Submitted = 2,
    [pbr::OriginalName("New")] New = 3,
    [pbr::OriginalName("PartialFilled")] PartialFilled = 4,
    [pbr::OriginalName("Filled")] Filled = 5,
    [pbr::OriginalName("PartialFilledCanceled")] PartialFilledCanceled = 6,
    [pbr::OriginalName("Canceled")] Canceled = 7,
    [pbr::OriginalName("Rejected")] Rejected = 8,
  }

  #endregion

  #region Messages
  public sealed partial class Order : pb::IMessage<Order> {
    private static readonly pb::MessageParser<Order> _parser = new pb::MessageParser<Order>(() => new Order());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Order> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.OrderReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Order() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Order(Order other) : this() {
      id_ = other.id_;
      instrument_ = other.instrument_;
      exchange_ = other.exchange_;
      counterId_ = other.counterId_;
      exchangeId_ = other.exchangeId_;
      note_ = other.note_;
      price_ = other.price_;
      avgExecutedPrice_ = other.avgExecutedPrice_;
      volume_ = other.volume_;
      executedVolume_ = other.executedVolume_;
      side_ = other.side_;
      timeCondition_ = other.timeCondition_;
      type_ = other.type_;
      status_ = other.status_;
      time_ = other.time_;
      latency_ = other.latency_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Order Clone() {
      return new Order(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private ulong id_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "instrument" field.</summary>
    public const int InstrumentFieldNumber = 2;
    private string instrument_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Instrument {
      get { return instrument_; }
      set {
        instrument_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "exchange" field.</summary>
    public const int ExchangeFieldNumber = 3;
    private global::Proto.Exchange exchange_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.Exchange Exchange {
      get { return exchange_; }
      set {
        exchange_ = value;
      }
    }

    /// <summary>Field number for the "counter_id" field.</summary>
    public const int CounterIdFieldNumber = 4;
    private string counterId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string CounterId {
      get { return counterId_; }
      set {
        counterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "exchange_id" field.</summary>
    public const int ExchangeIdFieldNumber = 5;
    private string exchangeId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ExchangeId {
      get { return exchangeId_; }
      set {
        exchangeId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "note" field.</summary>
    public const int NoteFieldNumber = 6;
    private string note_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Note {
      get { return note_; }
      set {
        note_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "price" field.</summary>
    public const int PriceFieldNumber = 7;
    private double price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "avg_executed_price" field.</summary>
    public const int AvgExecutedPriceFieldNumber = 8;
    private double avgExecutedPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double AvgExecutedPrice {
      get { return avgExecutedPrice_; }
      set {
        avgExecutedPrice_ = value;
      }
    }

    /// <summary>Field number for the "volume" field.</summary>
    public const int VolumeFieldNumber = 9;
    private int volume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Volume {
      get { return volume_; }
      set {
        volume_ = value;
      }
    }

    /// <summary>Field number for the "executed_volume" field.</summary>
    public const int ExecutedVolumeFieldNumber = 10;
    private int executedVolume_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ExecutedVolume {
      get { return executedVolume_; }
      set {
        executedVolume_ = value;
      }
    }

    /// <summary>Field number for the "side" field.</summary>
    public const int SideFieldNumber = 11;
    private global::Proto.Side side_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.Side Side {
      get { return side_; }
      set {
        side_ = value;
      }
    }

    /// <summary>Field number for the "time_condition" field.</summary>
    public const int TimeConditionFieldNumber = 12;
    private global::Proto.TimeCondition timeCondition_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.TimeCondition TimeCondition {
      get { return timeCondition_; }
      set {
        timeCondition_ = value;
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 13;
    private global::Proto.OrderType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.OrderType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 14;
    private global::Proto.OrderStatus status_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.OrderStatus Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "time" field.</summary>
    public const int TimeFieldNumber = 15;
    private ulong time_;
    /// <summary>
    ///google.protobuf.Timestamp time = 14;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "latency" field.</summary>
    public const int LatencyFieldNumber = 16;
    private int latency_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Latency {
      get { return latency_; }
      set {
        latency_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Order);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Order other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Instrument != other.Instrument) return false;
      if (Exchange != other.Exchange) return false;
      if (CounterId != other.CounterId) return false;
      if (ExchangeId != other.ExchangeId) return false;
      if (Note != other.Note) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Price, other.Price)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(AvgExecutedPrice, other.AvgExecutedPrice)) return false;
      if (Volume != other.Volume) return false;
      if (ExecutedVolume != other.ExecutedVolume) return false;
      if (Side != other.Side) return false;
      if (TimeCondition != other.TimeCondition) return false;
      if (Type != other.Type) return false;
      if (Status != other.Status) return false;
      if (Time != other.Time) return false;
      if (Latency != other.Latency) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0UL) hash ^= Id.GetHashCode();
      if (Instrument.Length != 0) hash ^= Instrument.GetHashCode();
      if (Exchange != 0) hash ^= Exchange.GetHashCode();
      if (CounterId.Length != 0) hash ^= CounterId.GetHashCode();
      if (ExchangeId.Length != 0) hash ^= ExchangeId.GetHashCode();
      if (Note.Length != 0) hash ^= Note.GetHashCode();
      if (Price != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Price);
      if (AvgExecutedPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(AvgExecutedPrice);
      if (Volume != 0) hash ^= Volume.GetHashCode();
      if (ExecutedVolume != 0) hash ^= ExecutedVolume.GetHashCode();
      if (Side != 0) hash ^= Side.GetHashCode();
      if (TimeCondition != 0) hash ^= TimeCondition.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Status != 0) hash ^= Status.GetHashCode();
      if (Time != 0UL) hash ^= Time.GetHashCode();
      if (Latency != 0) hash ^= Latency.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Id != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Id);
      }
      if (Instrument.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Instrument);
      }
      if (Exchange != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Exchange);
      }
      if (CounterId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CounterId);
      }
      if (ExchangeId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(ExchangeId);
      }
      if (Note.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Note);
      }
      if (Price != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(Price);
      }
      if (AvgExecutedPrice != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(AvgExecutedPrice);
      }
      if (Volume != 0) {
        output.WriteRawTag(72);
        output.WriteInt32(Volume);
      }
      if (ExecutedVolume != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(ExecutedVolume);
      }
      if (Side != 0) {
        output.WriteRawTag(88);
        output.WriteEnum((int) Side);
      }
      if (TimeCondition != 0) {
        output.WriteRawTag(96);
        output.WriteEnum((int) TimeCondition);
      }
      if (Type != 0) {
        output.WriteRawTag(104);
        output.WriteEnum((int) Type);
      }
      if (Status != 0) {
        output.WriteRawTag(112);
        output.WriteEnum((int) Status);
      }
      if (Time != 0UL) {
        output.WriteRawTag(120);
        output.WriteUInt64(Time);
      }
      if (Latency != 0) {
        output.WriteRawTag(128, 1);
        output.WriteInt32(Latency);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Id);
      }
      if (Instrument.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Instrument);
      }
      if (Exchange != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Exchange);
      }
      if (CounterId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CounterId);
      }
      if (ExchangeId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ExchangeId);
      }
      if (Note.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Note);
      }
      if (Price != 0D) {
        size += 1 + 8;
      }
      if (AvgExecutedPrice != 0D) {
        size += 1 + 8;
      }
      if (Volume != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Volume);
      }
      if (ExecutedVolume != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExecutedVolume);
      }
      if (Side != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Side);
      }
      if (TimeCondition != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TimeCondition);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Status != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (Time != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Time);
      }
      if (Latency != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Latency);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Order other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0UL) {
        Id = other.Id;
      }
      if (other.Instrument.Length != 0) {
        Instrument = other.Instrument;
      }
      if (other.Exchange != 0) {
        Exchange = other.Exchange;
      }
      if (other.CounterId.Length != 0) {
        CounterId = other.CounterId;
      }
      if (other.ExchangeId.Length != 0) {
        ExchangeId = other.ExchangeId;
      }
      if (other.Note.Length != 0) {
        Note = other.Note;
      }
      if (other.Price != 0D) {
        Price = other.Price;
      }
      if (other.AvgExecutedPrice != 0D) {
        AvgExecutedPrice = other.AvgExecutedPrice;
      }
      if (other.Volume != 0) {
        Volume = other.Volume;
      }
      if (other.ExecutedVolume != 0) {
        ExecutedVolume = other.ExecutedVolume;
      }
      if (other.Side != 0) {
        Side = other.Side;
      }
      if (other.TimeCondition != 0) {
        TimeCondition = other.TimeCondition;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Status != 0) {
        Status = other.Status;
      }
      if (other.Time != 0UL) {
        Time = other.Time;
      }
      if (other.Latency != 0) {
        Latency = other.Latency;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadUInt64();
            break;
          }
          case 18: {
            Instrument = input.ReadString();
            break;
          }
          case 24: {
            exchange_ = (global::Proto.Exchange) input.ReadEnum();
            break;
          }
          case 34: {
            CounterId = input.ReadString();
            break;
          }
          case 42: {
            ExchangeId = input.ReadString();
            break;
          }
          case 50: {
            Note = input.ReadString();
            break;
          }
          case 57: {
            Price = input.ReadDouble();
            break;
          }
          case 65: {
            AvgExecutedPrice = input.ReadDouble();
            break;
          }
          case 72: {
            Volume = input.ReadInt32();
            break;
          }
          case 80: {
            ExecutedVolume = input.ReadInt32();
            break;
          }
          case 88: {
            side_ = (global::Proto.Side) input.ReadEnum();
            break;
          }
          case 96: {
            timeCondition_ = (global::Proto.TimeCondition) input.ReadEnum();
            break;
          }
          case 104: {
            type_ = (global::Proto.OrderType) input.ReadEnum();
            break;
          }
          case 112: {
            status_ = (global::Proto.OrderStatus) input.ReadEnum();
            break;
          }
          case 120: {
            Time = input.ReadUInt64();
            break;
          }
          case 128: {
            Latency = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
