// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: PricingSpec.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from PricingSpec.proto</summary>
  public static partial class PricingSpecReflection {

    #region Descriptor
    /// <summary>File descriptor for PricingSpec.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PricingSpecReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFQcmljaW5nU3BlYy5wcm90bxIFUHJvdG8aDkV4Y2hhbmdlLnByb3RvGg1S",
            "ZXF1ZXN0LnByb3RvGgtSZXBseS5wcm90byL1AQoLUHJpY2luZ1NwZWMSDAoE",
            "bmFtZRgBIAEoCRISCgp1bmRlcmx5aW5nGAIgASgJEiIKBW1vZGVsGAMgASgO",
            "MhMuUHJvdG8uUHJpY2luZ01vZGVsEg8KB29wdGlvbnMYBCADKAkSDQoFZGVw",
            "dGgYBSABKAUSEAoIaW50ZXJ2YWwYBiABKAUSLAoJdGhlb190eXBlGAcgASgO",
            "MhkuUHJvdG8uVW5kZXJseWluZ1RoZW9UeXBlEhgKEHdhcm5fdGlja19jaGFu",
            "Z2UYCCABKAUSDwoHZWxhc3RpYxgJIAEoARIVCg1lbGFzdGljX2xpbWl0GAog",
            "ASgBIpcBCg5QcmljaW5nU3BlY1JlcRIgCgR0eXBlGAEgASgOMhIuUHJvdG8u",
            "UmVxdWVzdFR5cGUSIQoIZXhjaGFuZ2UYAiABKA4yDy5Qcm90by5FeGNoYW5n",
            "ZRIkCghwcmljaW5ncxgDIAMoCzISLlByb3RvLlByaWNpbmdTcGVjEgwKBG5h",
            "bWUYBCABKAkSDAoEdXNlchgFIAEoCSJUCg5QcmljaW5nU3BlY1JlcBIkCghw",
            "cmljaW5ncxgBIAMoCzISLlByb3RvLlByaWNpbmdTcGVjEhwKBnJlc3VsdBgC",
            "IAEoCzIMLlByb3RvLlJlcGx5KiAKDFByaWNpbmdNb2RlbBIHCgNCU00QABIH",
            "CgNDUlIQASpBChJVbmRlcmx5aW5nVGhlb1R5cGUSDAoITWlkcG9pbnQQABIO",
            "CgpCYXJ5Q2VudHJlEAESDQoJRGVwdGhCYXJ5EAJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Proto.ExchangeReflection.Descriptor, global::Proto.RequestReflection.Descriptor, global::Proto.ReplyReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.PricingModel), typeof(global::Proto.UnderlyingTheoType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.PricingSpec), global::Proto.PricingSpec.Parser, new[]{ "Name", "Underlying", "Model", "Options", "Depth", "Interval", "TheoType", "WarnTickChange", "Elastic", "ElasticLimit" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.PricingSpecReq), global::Proto.PricingSpecReq.Parser, new[]{ "Type", "Exchange", "Pricings", "Name", "User" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Proto.PricingSpecRep), global::Proto.PricingSpecRep.Parser, new[]{ "Pricings", "Result" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum PricingModel {
    [pbr::OriginalName("BSM")] Bsm = 0,
    [pbr::OriginalName("CRR")] Crr = 1,
  }

  public enum UnderlyingTheoType {
    [pbr::OriginalName("Midpoint")] Midpoint = 0,
    [pbr::OriginalName("BaryCentre")] BaryCentre = 1,
    [pbr::OriginalName("DepthBary")] DepthBary = 2,
  }

  #endregion

  #region Messages
  public sealed partial class PricingSpec : pb::IMessage<PricingSpec> {
    private static readonly pb::MessageParser<PricingSpec> _parser = new pb::MessageParser<PricingSpec>(() => new PricingSpec());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PricingSpec> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.PricingSpecReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpec() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpec(PricingSpec other) : this() {
      name_ = other.name_;
      underlying_ = other.underlying_;
      model_ = other.model_;
      options_ = other.options_.Clone();
      depth_ = other.depth_;
      interval_ = other.interval_;
      theoType_ = other.theoType_;
      warnTickChange_ = other.warnTickChange_;
      elastic_ = other.elastic_;
      elasticLimit_ = other.elasticLimit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpec Clone() {
      return new PricingSpec(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "underlying" field.</summary>
    public const int UnderlyingFieldNumber = 2;
    private string underlying_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Underlying {
      get { return underlying_; }
      set {
        underlying_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "model" field.</summary>
    public const int ModelFieldNumber = 3;
    private global::Proto.PricingModel model_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.PricingModel Model {
      get { return model_; }
      set {
        model_ = value;
      }
    }

    /// <summary>Field number for the "options" field.</summary>
    public const int OptionsFieldNumber = 4;
    private static readonly pb::FieldCodec<string> _repeated_options_codec
        = pb::FieldCodec.ForString(34);
    private readonly pbc::RepeatedField<string> options_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> Options {
      get { return options_; }
    }

    /// <summary>Field number for the "depth" field.</summary>
    public const int DepthFieldNumber = 5;
    private int depth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Depth {
      get { return depth_; }
      set {
        depth_ = value;
      }
    }

    /// <summary>Field number for the "interval" field.</summary>
    public const int IntervalFieldNumber = 6;
    private int interval_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Interval {
      get { return interval_; }
      set {
        interval_ = value;
      }
    }

    /// <summary>Field number for the "theo_type" field.</summary>
    public const int TheoTypeFieldNumber = 7;
    private global::Proto.UnderlyingTheoType theoType_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.UnderlyingTheoType TheoType {
      get { return theoType_; }
      set {
        theoType_ = value;
      }
    }

    /// <summary>Field number for the "warn_tick_change" field.</summary>
    public const int WarnTickChangeFieldNumber = 8;
    private int warnTickChange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WarnTickChange {
      get { return warnTickChange_; }
      set {
        warnTickChange_ = value;
      }
    }

    /// <summary>Field number for the "elastic" field.</summary>
    public const int ElasticFieldNumber = 9;
    private double elastic_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double Elastic {
      get { return elastic_; }
      set {
        elastic_ = value;
      }
    }

    /// <summary>Field number for the "elastic_limit" field.</summary>
    public const int ElasticLimitFieldNumber = 10;
    private double elasticLimit_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double ElasticLimit {
      get { return elasticLimit_; }
      set {
        elasticLimit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PricingSpec);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PricingSpec other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Underlying != other.Underlying) return false;
      if (Model != other.Model) return false;
      if(!options_.Equals(other.options_)) return false;
      if (Depth != other.Depth) return false;
      if (Interval != other.Interval) return false;
      if (TheoType != other.TheoType) return false;
      if (WarnTickChange != other.WarnTickChange) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Elastic, other.Elastic)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ElasticLimit, other.ElasticLimit)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Underlying.Length != 0) hash ^= Underlying.GetHashCode();
      if (Model != 0) hash ^= Model.GetHashCode();
      hash ^= options_.GetHashCode();
      if (Depth != 0) hash ^= Depth.GetHashCode();
      if (Interval != 0) hash ^= Interval.GetHashCode();
      if (TheoType != 0) hash ^= TheoType.GetHashCode();
      if (WarnTickChange != 0) hash ^= WarnTickChange.GetHashCode();
      if (Elastic != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Elastic);
      if (ElasticLimit != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ElasticLimit);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Underlying.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Underlying);
      }
      if (Model != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Model);
      }
      options_.WriteTo(output, _repeated_options_codec);
      if (Depth != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Depth);
      }
      if (Interval != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Interval);
      }
      if (TheoType != 0) {
        output.WriteRawTag(56);
        output.WriteEnum((int) TheoType);
      }
      if (WarnTickChange != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(WarnTickChange);
      }
      if (Elastic != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Elastic);
      }
      if (ElasticLimit != 0D) {
        output.WriteRawTag(81);
        output.WriteDouble(ElasticLimit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Underlying.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Underlying);
      }
      if (Model != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Model);
      }
      size += options_.CalculateSize(_repeated_options_codec);
      if (Depth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Depth);
      }
      if (Interval != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Interval);
      }
      if (TheoType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) TheoType);
      }
      if (WarnTickChange != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WarnTickChange);
      }
      if (Elastic != 0D) {
        size += 1 + 8;
      }
      if (ElasticLimit != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PricingSpec other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Underlying.Length != 0) {
        Underlying = other.Underlying;
      }
      if (other.Model != 0) {
        Model = other.Model;
      }
      options_.Add(other.options_);
      if (other.Depth != 0) {
        Depth = other.Depth;
      }
      if (other.Interval != 0) {
        Interval = other.Interval;
      }
      if (other.TheoType != 0) {
        TheoType = other.TheoType;
      }
      if (other.WarnTickChange != 0) {
        WarnTickChange = other.WarnTickChange;
      }
      if (other.Elastic != 0D) {
        Elastic = other.Elastic;
      }
      if (other.ElasticLimit != 0D) {
        ElasticLimit = other.ElasticLimit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 18: {
            Underlying = input.ReadString();
            break;
          }
          case 24: {
            model_ = (global::Proto.PricingModel) input.ReadEnum();
            break;
          }
          case 34: {
            options_.AddEntriesFrom(input, _repeated_options_codec);
            break;
          }
          case 40: {
            Depth = input.ReadInt32();
            break;
          }
          case 48: {
            Interval = input.ReadInt32();
            break;
          }
          case 56: {
            theoType_ = (global::Proto.UnderlyingTheoType) input.ReadEnum();
            break;
          }
          case 64: {
            WarnTickChange = input.ReadInt32();
            break;
          }
          case 73: {
            Elastic = input.ReadDouble();
            break;
          }
          case 81: {
            ElasticLimit = input.ReadDouble();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PricingSpecReq : pb::IMessage<PricingSpecReq> {
    private static readonly pb::MessageParser<PricingSpecReq> _parser = new pb::MessageParser<PricingSpecReq>(() => new PricingSpecReq());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PricingSpecReq> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.PricingSpecReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpecReq() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpecReq(PricingSpecReq other) : this() {
      type_ = other.type_;
      exchange_ = other.exchange_;
      pricings_ = other.pricings_.Clone();
      name_ = other.name_;
      user_ = other.user_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpecReq Clone() {
      return new PricingSpecReq(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Proto.RequestType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.RequestType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "exchange" field.</summary>
    public const int ExchangeFieldNumber = 2;
    private global::Proto.Exchange exchange_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.Exchange Exchange {
      get { return exchange_; }
      set {
        exchange_ = value;
      }
    }

    /// <summary>Field number for the "pricings" field.</summary>
    public const int PricingsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Proto.PricingSpec> _repeated_pricings_codec
        = pb::FieldCodec.ForMessage(26, global::Proto.PricingSpec.Parser);
    private readonly pbc::RepeatedField<global::Proto.PricingSpec> pricings_ = new pbc::RepeatedField<global::Proto.PricingSpec>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Proto.PricingSpec> Pricings {
      get { return pricings_; }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 4;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user" field.</summary>
    public const int UserFieldNumber = 5;
    private string user_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string User {
      get { return user_; }
      set {
        user_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PricingSpecReq);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PricingSpecReq other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Exchange != other.Exchange) return false;
      if(!pricings_.Equals(other.pricings_)) return false;
      if (Name != other.Name) return false;
      if (User != other.User) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Exchange != 0) hash ^= Exchange.GetHashCode();
      hash ^= pricings_.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (User.Length != 0) hash ^= User.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Exchange != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Exchange);
      }
      pricings_.WriteTo(output, _repeated_pricings_codec);
      if (Name.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Name);
      }
      if (User.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(User);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Exchange != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Exchange);
      }
      size += pricings_.CalculateSize(_repeated_pricings_codec);
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (User.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(User);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PricingSpecReq other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Exchange != 0) {
        Exchange = other.Exchange;
      }
      pricings_.Add(other.pricings_);
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.User.Length != 0) {
        User = other.User;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            type_ = (global::Proto.RequestType) input.ReadEnum();
            break;
          }
          case 16: {
            exchange_ = (global::Proto.Exchange) input.ReadEnum();
            break;
          }
          case 26: {
            pricings_.AddEntriesFrom(input, _repeated_pricings_codec);
            break;
          }
          case 34: {
            Name = input.ReadString();
            break;
          }
          case 42: {
            User = input.ReadString();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PricingSpecRep : pb::IMessage<PricingSpecRep> {
    private static readonly pb::MessageParser<PricingSpecRep> _parser = new pb::MessageParser<PricingSpecRep>(() => new PricingSpecRep());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PricingSpecRep> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Proto.PricingSpecReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpecRep() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpecRep(PricingSpecRep other) : this() {
      pricings_ = other.pricings_.Clone();
      Result = other.result_ != null ? other.Result.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PricingSpecRep Clone() {
      return new PricingSpecRep(this);
    }

    /// <summary>Field number for the "pricings" field.</summary>
    public const int PricingsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Proto.PricingSpec> _repeated_pricings_codec
        = pb::FieldCodec.ForMessage(10, global::Proto.PricingSpec.Parser);
    private readonly pbc::RepeatedField<global::Proto.PricingSpec> pricings_ = new pbc::RepeatedField<global::Proto.PricingSpec>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Proto.PricingSpec> Pricings {
      get { return pricings_; }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 2;
    private global::Proto.Reply result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Proto.Reply Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PricingSpecRep);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PricingSpecRep other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!pricings_.Equals(other.pricings_)) return false;
      if (!object.Equals(Result, other.Result)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= pricings_.GetHashCode();
      if (result_ != null) hash ^= Result.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      pricings_.WriteTo(output, _repeated_pricings_codec);
      if (result_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += pricings_.CalculateSize(_repeated_pricings_codec);
      if (result_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Result);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PricingSpecRep other) {
      if (other == null) {
        return;
      }
      pricings_.Add(other.pricings_);
      if (other.result_ != null) {
        if (result_ == null) {
          result_ = new global::Proto.Reply();
        }
        Result.MergeFrom(other.Result);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            pricings_.AddEntriesFrom(input, _repeated_pricings_codec);
            break;
          }
          case 18: {
            if (result_ == null) {
              result_ = new global::Proto.Reply();
            }
            input.ReadMessage(result_);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
